# Generated by Django 6.0.5 on 2026-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskdetail_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='assigned_to',
            field=models.CharField(default='ami emni disi', max_length=100),
            preserve_default=False,
        ),
    ]
