# Generated by Django 6.0.5 on 2026-05-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskdetail_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
