# Generated by Django 6.0.4 on 2026-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(to='tasks.employees'),
        ),
    ]
